export const FETCH_BUILDINGS = 'FETCH_BUILDINGS'
export const FETCH_BUILDINGS_SUCCESS = 'FETCH_BUILDINGS_SUCCESS'
export const FETCH_BUILDINGS_ERROR = 'FETCH_BUILDINGS_ERROR'
export const FETCH_SLOT_FROM_BUILDINGS = 'FETCH_SLOT_FROM_BUILDINGS'
